# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-05 16:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='previousvenue',
            name='venue_name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
