# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-23 06:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_auto_20171207_0855'),
    ]

    operations = [
        migrations.RenameField(
            model_name='currentshow',
            old_name='endDate',
            new_name='end_date',
        ),
        migrations.RenameField(
            model_name='currentshow',
            old_name='startDate',
            new_name='start_date',
        ),
    ]
