# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-25 12:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_auto_20171223_0233'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='currentshow',
            options={'verbose_name_plural': 'Current Shows'},
        ),
        migrations.AlterModelOptions(
            name='previousvenue',
            options={'ordering': ['venue_name'], 'verbose_name_plural': 'Previous Venues'},
        ),
    ]
