# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-16 00:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_auto_20171225_0701'),
    ]

    operations = [
        migrations.AddField(
            model_name='previousvenue',
            name='city',
            field=models.CharField(default='Riviera Beach', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='previousvenue',
            name='state',
            field=models.CharField(default='FL', max_length=2),
            preserve_default=False,
        ),
    ]
