# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-05 16:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artwork',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artwork_type', models.CharField(choices=[('ac', 'Acrylic'), ('photo', 'Photograph'), ('wc', 'Watercolor')], max_length=5)),
                ('image', models.ImageField(null=True, upload_to='shows/')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=255)),
                ('size', models.CharField(blank=True, max_length=50)),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=8)),
            ],
        ),
    ]
