# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-07 14:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artwork',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=255)),
                ('size', models.CharField(blank=True, max_length=50)),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('my_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'artwork',
                'ordering': ['my_order'],
            },
        ),
        migrations.CreateModel(
            name='Acrylic',
            fields=[
                ('artwork_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='art.Artwork')),
                ('image', models.ImageField(null=True, upload_to='artwork/ac/')),
            ],
            bases=('art.artwork',),
        ),
        migrations.CreateModel(
            name='Photograph',
            fields=[
                ('artwork_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='art.Artwork')),
                ('image', models.ImageField(null=True, upload_to='artwork/ph/')),
            ],
            bases=('art.artwork',),
        ),
        migrations.CreateModel(
            name='Watercolor',
            fields=[
                ('artwork_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='art.Artwork')),
                ('image', models.ImageField(null=True, upload_to='artwork/wc/')),
            ],
            bases=('art.artwork',),
        ),
    ]
