# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-23 05:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True)),
                ('my_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'bio',
                'ordering': ['my_order'],
            },
        ),
        migrations.CreateModel(
            name='Friends',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('my_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'friends',
                'ordering': ['my_order'],
            },
        ),
    ]
