# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-23 07:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0002_friends_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bio',
            options={'verbose_name_plural': 'bio'},
        ),
        migrations.RemoveField(
            model_name='bio',
            name='my_order',
        ),
    ]
