# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-23 08:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0004_auto_20171223_0314'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bio',
            options={'verbose_name_plural': 'bio'},
        ),
        migrations.AlterModelOptions(
            name='selfphoto',
            options={'verbose_name_plural': 'Self Photo'},
        ),
        migrations.RenameField(
            model_name='bio',
            old_name='description',
            new_name='text',
        ),
    ]
